#------------------------------------------------------------------------------
# Appveyor configuration file for cpp-ethereum.
#
# The documentation for cpp-ethereum is hosted at:
#
# http://www.ethdocs.org/en/latest/ethereum-clients/cpp-ethereum/
#
# TODO - We are currently disabling EVMJIT, because of https://github.com/ethereum/webthree-umbrella/issues/549
#
# (c) 2016 cpp-ethereum contributors.
#------------------------------------------------------------------------------

os: Visual Studio 2015
configuration:
    - Release
install:
    - git submodule update --init --recursive
    - cmake -P webthree-helpers\deps\install_deps.cmake
before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" .. -DGUI=0 -DTOOLS=0 -DSOLIDITY=0 -DEVMJIT=0
    - git clone https://github.com/ethereum/tests.git
build_script:
    - msbuild  C:\projects\webthree-umbrella\build\cpp-ethereum.sln
